### ISSUE TITLE
Prepare for a possible core merge

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/oEmbed-API#51]
Not in a specific order: 
* [x] Create `WP_oEmbed_Legacy_Controller`, possibly removing `WP_oEmbed_Plugin` (#35)
* [x] Having the plugin active after merge shouldn't result in a fatal error (#50)
* [ ] Inline Docs review (#46)
* [ ] Security Audit (#48)
* [x] User Tests (#49)
* [x] Increase usage numbers (#54)
* [x] Write [a post](https://make.wordpress.org/flow/2015/09/12/embeds-visual-survey-of-the-oembed-feature-plugin-macnchrome-iphone-5s/) on Make/Flow about the plugin
* [x] Write merge proposal (#52)

Plugin merge window is probably already in a couple of weeks so we should be ready
